site_name: Tecnun-eRacing Wiki
site_url: https://ozuba.eus/eRacingWiki
theme:
  name: material
  language: es
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg

  palette:
    scheme: default
    primary: black

  font: false

  features:
  - navigation.tabs



nav:
  - Home: index.md
  - Electronics:
    - Electronics/electronics.md
    - Systems:
      - Pedal: Electronics/SYSTEMS/PEDAL/pedal.md
      - Ecu: Electronics/SYSTEMS/ECU/ecu.md
    - Library: 
       - CAN: Electronics/LIBRARY/canbus.md
    - C: Electronics/GNUC/gnuc.md
  - Driverless: Driverless/driverless.md



extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/kicanvas.js
extra:
  generator: false
